# Generated by Django 5.1.7 on 2026-09-11 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_home', '0009_question_participanttest_participantanswer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=False, help_text='Enable/disable problem statement visibility for this track')),
                ('file', models.FileField(blank=True, help_text='Problem Statement document', null=True, upload_to='problem_statements/')),
                ('qualifying_status', models.CharField(blank=True, default='Pending', help_text='Qualifying status or message for this track', max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problemstatementsection',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='staff_home.problemstatementconfig'),
        ),
        migrations.AddField(
            model_name='problemstatementconfig',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='staff_home.track'),
        ),
        migrations.AddField(
            model_name='problemstatementsection',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='staff_home.track'),
        ),
        migrations.AddField(
            model_name='resource',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='staff_home.track'),
        ),
    ]
