# Generated by Django 5.1.7 on 2026-09-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_home', '0011_migrate_existing_data_to_default_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='qualifying_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('archived', 'Archived'), ('rejected', 'Rejected')], default='pending', help_text='Qualifying status for this track', max_length=50),
        ),
    ]
