# Generated by Django 5.1.7 on 2026-09-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_home', '0011_migrate_existing_data_to_default_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('attempts', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(default='announcement', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='track',
            name='qualifying_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('archived', 'Archived'), ('rejected', 'Rejected')], default='pending', help_text='Qualifying status for this track', max_length=50),
        ),
    ]
