# Generated by Django 5.1.7 on 2026-10-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_home', '0012_alter_track_qualifying_status'),
        ('staff_home', '0012_emaillog_alter_track_qualifying_status'),
    ]

    operations = [
    ]
