# Generated by Django 4.2.11 on 2026-10-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_home', '0014_paymentconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='event_year',
            field=models.IntegerField(default=2026),
        ),
    ]
