# Generated by Django 4.2.11 on 2026-10-09 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_home', '0015_alter_test_event_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_registration_open', models.BooleanField(default=True, help_text='Master toggle to start/stop all event registrations')),
                ('sim2real_enabled', models.BooleanField(default=True, help_text='Enable/disable registration for Sim2Real track')),
                ('ideathon_enabled', models.BooleanField(default=True, help_text='Enable/disable registration for Sim2Real Ideathon track')),
                ('closed_message', models.TextField(default='Registrations for this track are currently closed by organizers.', help_text='Notice shown when registration is closed')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_track', models.ForeignKey(blank=True, help_text='Default selected track for new registrations', null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff_home.track')),
            ],
        ),
    ]
