# Generated by Django 5.1.7 on 2026-08-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_profile', '0004_team_is_verified_team_payment_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='event_year',
            field=models.IntegerField(default=2025),
        ),
    ]
