# Generated by Django 5.1.7 on 2026-09-11 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_home', '0010_track_resource_description_and_more'),
        ('team_profile', '0005_team_event_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='staff_home.track'),
        ),
    ]
