# Generated by Django 4.2.11 on 2026-10-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_profile', '0007_team_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='policy_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when team accepted policies and code of conduct', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='event_year',
            field=models.IntegerField(default=2026),
        ),
    ]
