# Generated by Django 4.2.11 on 2026-10-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_profile', '0008_team_policy_accepted_at_alter_team_event_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='round1_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='round1_status',
            field=models.CharField(choices=[('pending', 'Pending / Under Evaluation'), ('disqualified', 'Disqualified'), ('qualified_r2', 'Qualified for Round 2'), ('waitlist', 'Waitlist'), ('moved_ideathon', 'Moved for Sim2Real Ideathon'), ('moved_waitlist_r2', 'Moved from Waitlist to Round 2')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='round2_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='round2_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('qualified', 'Qualified'), ('disqualified', 'Disqualified')], default='pending', max_length=50),
        ),
    ]
