# Generated by Django 4.2.11 on 2026-09-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_event_year_userprofile_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='event_year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
